### ISSUE TITLE
Lettuce user support model

### ISSUE THREAD

**Issue by mp911de** [redis/lettuce#1467]
Dear community, 

Lettuce started as a non-blocking driver supporting some basic Redis operations. Over time, it grew to a driver that is able to operate in a majority of operation modes. With its growth, the userbase and amount of support requests ("I have a timeout", "Can't connect", "How do I …?") increased. 

Lettuce is maintained by a single person - me. Adding features, fixing bugs works well in this mode of operation. Answering support requests does not. Now it's time to reconsider the user support model as it doesn't scale with a single person maintaining the project in their free time.

I'm happy to discuss suggestions.

**Comment by dengliming** [comment]
Have you considered inviting some collaborators?

**Comment by mp911de** [comment]
Collaborators are always welcome and at times, there are some folks who contribute multiple times. Finding folks who want to contribute regularly is the hard bit. Giving push permissions is a matter of trust and requires that all contributors share a similar vision/code style to keep a consistent code and feature style.

**Comment by amit-github-personal** [comment]
Hey, I would love to contribute in your project

**Comment by mp911de** [comment]
Great to hear. A good starting point is having a look into the open issues, mostly bug reports, reviewing pull requests to get an idea of the Lettuce anatomy.

**Comment by sokomishalov** [comment]
It is a lot of pain to support such a huge open-source project.
BTW recently I've read the great article of redis creator Salvatore Sanfilippo (aka antirez) about such troubles
http://antirez.com/news/134
But let me ask maybe a stupid question
Since lettuce is a crucial part of spring ecosystem de facto (e.g. used by spring-data under the hood), why shouldn't spring team and community support it as one of the projects?

**Comment by mp911de** [comment]
While Salvatore's motivation is a bit more on a personal expression note, my motivation is contributing back to the community. Spring usage forms only a small fraction of the user-base. The Spring team typically builds integrations on top of drivers, they aren't building drivers themselves. You could argue the same way that Spring/Micronaut/Helidon build heavily on top of JPA and JDBC, so why don't they maintain those projects.

**Comment by mp911de** [comment]
@sokomishalov @dengliming you folks contributed already a lot to Lettuce. Would you like to become a core contributor at some point in time? Such a step clearly requires a bit more communication on particular issues, but that would be a logical step to me.

**Comment by dengliming** [comment]
@mp911de I would say yes. and happy to see that. Personally, I am a fan of Redis and I have recently been active in contributing to the client for [Redis modules](https://redis.io/modules) . Such as [redisearch](https://github.com/RediSearch/redisearch-go). It would be a great pleasure for me If I can work with you to make the Lettuce community better. Thanks : )

**Comment by sokomishalov** [comment]
@mp911de well, I would say yes too. I would glad to spend some free time by helping you and community to make the driver be even better. Thanks!

**Comment by mp911de** [comment]
Please welcome two new contributors, @sokomishalov and @dengliming 👏 👍

**Comment by cjs1992-github** [comment]
@mp911de  Hello, I want to be a contributor to your project and work hard to commit. Do you have any requirements that you can become a commit after meeting the requirements?

**Comment by mp911de** [comment]
Thanks for your interest. The only requirement is to follow our [contribution guidelines](https://github.com/lettuce-io/lettuce-core/blob/main/.github/CONTRIBUTING.md). Other than that, looking forward to reviewing your first pull request.

**Comment by tishun** [comment]
Closing this as Redis is now maintaining the Lettuce client.
As before - contributions are more than welcome and will always be.
