### ISSUE TITLE
Continue firing what read at channelRead method in CommandHandler so that customerized handler can receive messages

### ISSUE THREAD

**Issue by maozhen520** [redis/lettuce#1825]
## Feature Request

 
I added IdleStateHandler to pipeLine to moniter "idle state" ,but could not get real 'readIdle' , because IdleStateHandler could not receive msg in channleRead method.

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.
