### ISSUE TITLE
Request queue size is not cleared on reconnect

### ISSUE THREAD

**Issue by Hixon10** [redis/lettuce#1843]
## Bug Report

1. There is a Java (spring) service, which uses Redis cluster with help lettuce. 
2. We have a setting `spring.redis.lettuce.pool.maxActive == 100_000`
2. At some moment, the service lose network connectivity to one of redis cluster master nodes. 
3. The service has a bunch of background queries, which are executed periodically (e.g. we execute `ping` query each second). 
4. After some time, `io.lettuce.core.protocol.DefaultEndpoint#QUEUE_SIZE` is equal to `100_000` for some channels
5. As result, the service cannot execute any queries, using this connection. We got an error, like `Request queue size exceeded: 100000. Commands are not accepted until the queue size drops.`
6. After some time, the network connective issue is resolved. 
7. The problem is, that the application still has `io.lettuce.core.protocol.DefaultEndpoint#QUEUE_SIZE = 100_000`. If I manually set this field to `0`, the application starts working. 

#### Environment

- Lettuce version(s): 6.1.2.RELEASE
- Redis version: 6.2.5

Maybe, it is similar to https://github.com/lettuce-io/lettuce-core/issues/616

**Comment by mp911de** [comment]
Lettuce auto-reconnects and replays commands upon reconnect and that should drain the queue.

**Comment by tishun** [comment]
@Hixon10 are you able to provide a reproducible example where this problem can be examined?

**Comment by Hixon10** [comment]
@tishun unfortunately, no. It was long time ago, I don't have any context for this issue anymore.

**Comment by tishun** [comment]
> @tishun unfortunately, no. It was long time ago, I don't have any context for this issue anymore.

Thank you. I will be closing this for now and if somebody else runs into this again we can reopen.
