### ISSUE TITLE
It is recommended that the Lettuce community establish a formal organization for day-to-day operations.

### ISSUE THREAD

**Issue by cjs1992-github** [redis/lettuce#1889]
Recently, because of the project, lettuce is used a lot and found that lettuce is very good. However, after careful inspection of the community, it is found that the community has not set up a formal organization. I think a project needs more people to get bigger and stronger, I don't know.
Do you have any idea of setting up a SIG or PMC and running it in the community in this way?

**Comment by cjs1992-github** [comment]
I think lettuce is a very good redis client, it basically contains the most advanced java technology, is the best redis client.
I work for Huawei Technologies Co., Ltd. Our department attaches great importance to the Lettuce project and has promoted it to the company as a key sustainable project.
This project will be maintained in Huawei's corporate-level community. In other words, letuce will be maintained as Huawei's corporate-level software. We have an internal SIG organization.
and PMC for development. If you need enough contributors to work together, I'll advise the company, a team of component contributors to work together to maintain the software, if you need it.
At the same time, on behalf of our department, I invite you to do more communication with us, including but not limited to community, email, video conference, and even come to China! We expect letuce to get better and better.

**Comment by mp911de** [comment]
Thanks a lot. Getting more involvement is greatly appreciated and happy to provide further guidance. At the moment, this project has a single active contributor, other folks show up once or once in a while and there are not sufficient people that could form a proper organization.

**Comment by uglide** [comment]
I'm closing this because Redis Inc. is now officially maintaining the project. Please reach out if you have any questions or suggestions.
