### ISSUE TITLE
Add support for Redis 7 sharded Pub/Sub

### ISSUE THREAD

**Issue by mp911de** [redis/lettuce#1984]
See https://redis.io/topics/pubsub#sharded-pubsub

For the Cluster Pub/Sub, we likely need to only consider keys for routing as Cluster Pub/Sub intentionally drops the slot hash calculation.

**Comment by Dmdl** [comment]
Do we know when will lettuce support sharded Pub/Sub?

**Comment by jthacker2** [comment]
want to use this as well, any plan for support?

**Comment by prashanth-srinivasan1** [comment]
@mp911de is there any plan to implement this in the near future?

**Comment by adamsau** [comment]
any updates?

**Comment by adamsau** [comment]
> This feature requires a bit of design. While there is an intent to implement this, there's no time-line as this project is maintained in our spare time.

is it possible to submit a PR on this? any specific design decision we need to be aware? @mp911de

**Comment by mp911de** [comment]
Happy to review a pull request.

**Comment by tishun** [comment]
The sharded pub/sub should be handled by

- #2758 
- #2757 
- #2759 
- #2756 
- #2776 

Duplicate of #2762
