### ISSUE TITLE
Routing XREADGROUP command in Redis cluster

### ISSUE THREAD

**Issue by adiamzn** [redis/lettuce#2140]
#### Current Behavior
When using redis cluster,
it seems that the hash slot to which the XREADGROUP command is routed to is calculated using the consumer group rather than the stream.
This can be seen here [xreadgroup in RedisCommandBuilder](https://github.com/lettuce-io/lettuce-core/blob/main/src/main/java/io/lettuce/core/RedisCommandBuilder.java#L3006 ). where consumer.group is added to args with addKey.

</details>

#### Expected behavior/code
The XREADGROUP command should be routed based on stream and not consumer group.

#### Environment

- Lettuce version(s): 6.1.8.RELEASE
- Redis version: 6.x

#### Possible Solution
perhaps converting the consumer group and consumer name to strings and adding to xreadargs with add() instead of addKey()

**Comment by mp911de** [comment]
That's a bug. The consumer group could be a `byte[]` or a `String` and we want to give users a sense of flexibility here.
