### ISSUE TITLE
The socket channels to redis sentinels would increasing unlimitedly.

### ISSUE THREAD

**Issue by leonlibraries** [redis/lettuce#2193]
## Bug Report

The socket channels to redis sentinels would increasing unlimitedly, especially when I use object pool.

#### Current Behavior

I trace the function of borrowing connection from the pool , I've found the socket channel from client to redis sentinel will be created when building every single one connection in the pool. And the channel group is never under control by GenericObjectPoolConfig.

My question is How could I avoid that connections to redis sentinels increasing unlimitedly?

<details>
<summary>Stack trace</summary>

```java
class ChannelGroupListener extends ChannelInboundHandlerAdapter {

    private final ChannelGroup channels;

    private final EventBus eventBus;

    public ChannelGroupListener(ChannelGroup channels, EventBus eventBus) {
        this.channels = channels;
        this.eventBus = eventBus;
    }
   ...
}
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Environment

- Lettuce version(s): [e.g. 6.1.8.RELEASE]
- Redis version: [e.g. 4.0.8]

**Comment by luis6156** [comment]
I am also facing the same issue, since version 6.1.0.M1 a lot of sockets seem to be opened, hence I run into an error as the maximum number of open sockets is reached.

**Comment by mp911de** [comment]
Can you provide a minimal reproducer that shows how you use Lettuce?

**Comment by luis6156** [comment]
Of course, thank you for the quick response.

```@Bean
public RedisConnectionFactory redisConnectionFactory() {

    org.springframework.data.redis.connection.RedisConfiguration redisConfiguration;
    
    RedisStandaloneConfiguration redisStandaloneConfiguration = new RedisStandaloneConfiguration();
    redisStandaloneConfiguration.setHostName(redisHost);
    redisStandaloneConfiguration.setPort(redisPort);
    redisStandaloneConfiguration.setPassword(password);

    redisConfiguration = redisStandaloneConfiguration;

    LettuceClientConfiguration.LettuceClientConfigurationBuilder lettuceClientConfigurationBuilder =
        LettuceClientConfiguration.builder()
            .commandTimeout(Duration.of(redisCommandTimeout, ChronoUnit.SECONDS));

    LettuceClientConfiguration lettuceClientConfiguration = lettuceClientConfigurationBuilder.build();

    LettuceConnectionFactory lettuceConnectionFactory = new LettuceConnectionFactory(redisConfiguration, lettuceClientConfiguration);
    lettuceConnectionFactory.setDatabase(database);

    return lettuceConnectionFactory;
}

**Comment by mp911de** [comment]
The example code doesn't match anything pooling related. `ChannelGroupListener` is a collector to be able to close all open connections, not intended for pooling though.

Let me know whether there's still something left to do here.
