### ISSUE TITLE
multi-threads share one connection, async command xadd writeandflush success,but redis stream queue has no data

### ISSUE THREAD

**Issue by phlahut** [redis/lettuce#2195]
#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
   one thread use common connection async command and redis-future blocking read data from redis-stream queue
```
![image](https://user-images.githubusercontent.com/21032464/190377337-8d384b2e-c00f-4ab7-817f-fc3a11b46645.png)

```java
   and other thread the common connection async command to send xadd cmd to write data to redis-stream queue
```
![image](https://user-images.githubusercontent.com/21032464/190378105-d79853d2-8d7c-42e0-b0d9-43e33faa4c85.png)

```java
   and  i use wireshark to grab network data package, it shows xadd cmd send to redis successful and redis response ack, but in redis-stream queue has data 
```
![image](https://user-images.githubusercontent.com/21032464/190379346-2eb3e894-5bf2-4e5e-8242-4fc099278a88.png)

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Environment

- Lettuce version(s): [e.g. 5.0.0.RELEASE, 4.2.2.Final]
- Redis version: [e.g. 4.0.9]

**Comment by mp911de** [comment]
Have you been able to reproduce the issue with `redis-cli`?

**Comment by phlahut** [comment]
> Have you been able to reproduce the issue with `redis-cli`?
first：subscribe one queue called GlobalConfig.streamRecvQueue success
![image](https://user-images.githubusercontent.com/21032464/190539718-a5fc8be5-a731-4b86-a4ef-1ac750013591.png)

second：use redis-cli execute XADD to write data to GlobalConfig.streamRecvQueue
![image](https://user-images.githubusercontent.com/21032464/190539942-55b73b4d-95d5-4cca-a374-20638f29ff04.png)

then: see the code logic，on received data from  GlobalConfig.streamRecvQueue queue, it will submit a task to thread pool to send data to GlobalConfig.streamSendQueue queue, but in redis GlobalConfig.streamSendQueue queue has no data
![image](https://user-images.githubusercontent.com/21032464/190538824-842dfaa3-808a-4323-a747-999871ce6726.png)

wireshark: shows send data to GlobalConfig.streamSendQueue queue cmd success
![image](https://user-images.githubusercontent.com/21032464/190540757-41952a21-0289-4530-a38a-98b3b79a6744.png)

redis-cli: show GlobalConfig.streamSendQueue queue has no data
![image](https://user-images.githubusercontent.com/21032464/190541769-deb09b3a-aff0-4591-9df9-4e445fc73187.png)

send logic:
![image](https://user-images.githubusercontent.com/21032464/190541899-585edc10-3121-4e0b-8a10-fb39f96d04cc.png)

**Comment by mp911de** [comment]
Can you provide your Java code as text instead of screenshot? I do not want to type everything into my IDE to reproduce the case.

**Comment by phlahut** [comment]
many thanks , code as follow, you may be modify some code, like subscribe part, [handler.handle] can be changed by threadpool to invoke [sendMessage]


1、create connection:
`
 public RedisStreamMqClient(String url) {
        this.client = RedisClient.create(url);
        this.connection = this.client.connect();
    }
`

2、create queue
`
    public void createQueue(Queue queue, boolean existedOk) {
        RedisAsyncCommands<String, String> commands = this.connection.async();
        StringCodec codec = StringCodec.UTF8;
        CommandArgs<String, String> args = new CommandArgs<>(codec)
                .add(CommandKeyword.CREATE)
                .add(queue.getName())
                .add(queue.getGroup())
                .add(queue.getConsumeId());
        if (queue.isMkStream()) {
            args.add("MKSTREAM");
        }
        RedisFuture<String> future = commands.dispatch(CommandType.XGROUP, new StatusOutput<>(codec), args);
        try {
            future.get();
        } catch (ExecutionException e) {
            if (existedOk && StringUtils.containsIgnoreCase(e.getMessage(), SEARCH_MSG)) {
                return;
            }
            throw new RuntimeException(e);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }
`

3、subscribe queue
`
  public void subscribeQueue(Consumer consumer,XReadGroupHandler handler,ExceptionHandler exceptionHandler) {
        Queue queue = Queue.builder()
                .name(consumer.getQueue())
                .group(consumer.getGroup())
                .build();
        createQueue(queue, true);
        RedisAsyncCommands<String, String> commands = this.connection.async();
        StringCodec codec = StringCodec.UTF8;
        CommandArgs<String, String> args = new CommandArgs<>(codec)
                .add(CommandKeyword.GROUP)
                .add(consumer.getGroup())
                .add(consumer.getName());
        if (consumer.isNoAck()) { args.add(CommandKeyword.NOACK); }
        if (consumer.isBlock()) { args.add(CommandKeyword.BLOCK).add(0); }
        args.add(CommandKeyword.COUNT)
                .add(consumer.getCount())
                .add("STREAMS")
                .add(consumer.getQueue())
                .add(consumer.getConsumeId());
        while (true) {
            try {
                RedisFuture<List<Object>> future = commands.dispatch(CommandType.XREADGROUP, new NestedMultiOutput<>(codec), args);
                List<Object> consumedObjects = future.get();
                XReadGroupResponse response = XReadGroupResponse.fromOutput((List) consumedObjects.get(0));
                String[] messageIds = response.getMessageIds().toArray(new String[0]);
                ackMessage(consumer.getQueue(), consumer.getGroup(), messageIds);
                handler.handle(response);
                log.info("recv-----------------");
            } catch (InterruptedException | ExecutionException e) {
                exceptionHandler.handle(e);
                try {
                    Thread.sleep(consumer.getDelay());
                } catch (InterruptedException ex) {
                    throw new RuntimeException(ex);
                }
                createQueue(queue, true);
            }
        }
    }
`

4、send data
`
  public String sendMessage(Message message) {
        RedisAsyncCommands<String, String> commands = this.connection.async();
        XAddArgs addArgs = XAddArgs.Builder
                .maxlen(message.getMaxLength())
                .approximateTrimming(message.isApproximateTrimming());
        List<Object> keysAndValues = new ArrayList<>(Arrays.asList(message.getKeysAndValues()));
        keysAndValues.add("request_id");
        keysAndValues.add(message.getRequestId());
        Object[] data = keysAndValues.toArray(new Object[0]);
        RedisFuture<String> future =
                commands.xadd(message.getQueue(), addArgs, data);
        try {
            String ret = future.get();
            return ret;
        } catch (InterruptedException | ExecutionException e) {
            throw new RuntimeException(e);
        }
    }
`

**Comment by phlahut** [comment]
> Can you provide your Java code as text instead of screenshot? I do not want to type everything into my IDE to reproduce the case.

hi, i have provide the sample code, is it useful?

**Comment by mp911de** [comment]
I was not able to reproduce the issue. Having a reproducer would be useful to proceed here.
