### ISSUE TITLE
Add "username" setting support to Sentinel mode

### ISSUE THREAD

**Issue by georgelupu** [redis/lettuce#2285]
## Feature Request
Add "setSentinelUsername" method to Sentinel mode

#### Is your feature request related to a problem? Please describe
Latest Redis (6+) servers have ACL support which allows us to have in the database other users than the "default" one, but the current Lettuce client driver implementation does not allow to provide the "username" under [RedisSentinelConfiguration](https://docs.spring.io/spring-data/redis/docs/current-SNAPSHOT/api/org/springframework/data/redis/connection/RedisSentinelConfiguration.html) class.
As result only the "default" db user can be used with the Lettuce driver in order to connect to Sentinel - which is a concern for DBOps folks who do not want to share "default" root/admin account with the application developers.

#### Describe the solution you'd like
Today, we can only provide setSentinelPassword config in [RedisSentinelConfiguration](https://docs.spring.io/spring-data/redis/docs/current-SNAPSHOT/api/org/springframework/data/redis/connection/RedisSentinelConfiguration.html) class. 
Please add "setSentinelUsername" method support as well. Thank you!

#### Describe alternatives you've considered
No alternatives are available at the moment except using the "default" redis db user for connecting to Sentinel.

**Comment by castlering97** [comment]
Hi @mp911de. I would like to work on this issue if it's okay.
(And I am a beginner in open source, so I would be really glad if you could give me any kind of guidance =])

**Comment by tishun** [comment]
> Hi @mp911de. I would like to work on this issue if it's okay. (And I am a beginner in open source, so I would be really glad if you could give me any kind of guidance =])

Please submit a PR if you are still considering working on this

**Comment by ggivo** [comment]
Referred configuration class [RedisSentinelConfiguration](https://docs.spring.io/spring-data/redis/docs/current-SNAPSHOT/api/org/springframework/data/redis/connection/RedisSentinelConfiguration.html) is actually part of spring-data-redis.

It looks like support for providing a sentinel username in addition to the password  is already added with [commit](https://github.com/spring-projects/spring-data-redis/commit/f333b184a52e26e1f092a2d6eeac7296309f801d)
closing [issue](https://github.com/spring-projects/spring-data-redis/issues/2218)

Here is also more up-to-date link to [RedisSentinelConfiguration (Spring Data Redis 3.3.5 API)](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/connection/RedisSentinelConfiguration.html)
