### ISSUE TITLE
connections by nodeId when using redis cluster on Mesh

### ISSUE THREAD

**Issue by ramaraochavali** [redis/lettuce#2287]
When redis cluster is accessed via a proxy like Envoy, when Cluster Slots returns Slot with NULL as preferred endpoint (or local host as suggested by redis cluster docs behind[ load balancer](https://redis.io/commands/cluster-slots/)) with same port for all slots, lettuce is reusing the connection across slots because every node has same host and port (and connection key becomes same i.e. host, port). 

This is a problem because, lettuce creates/uses the same connection to different nodes in cluster while connecting to Envoy proxy. We would like lettuce to create different connections if the key hashes to a slot on a different node so that we do not build up a single pipeline to multiple upstream hosts (causing HOL blocking issue with slow/non responsive upstream redis).

I see that there is a way to getConnection by nodeId (connection keyed by node id). How do we ensure we get connections by nodeID

Basically our goal is when cluster slots return the following output

```
  // 1) 1) (integer) 0                                      <-- start slot range
  //    2) (integer) 5460                                   <-- end slot range
  //
  //    3) 1) "127.0.0.1"                                   <-- primary slot IP ADDR(HOSTNAME)
  //       2) (integer) 30001                               <-- primary slot PORT
  //       3) "09dbe9720cda62f7865eabc5fd8857c5d2678366"
  //
  //    4) 1) "127.0.0.1"                                   <-- replica slot IP ADDR(HOSTNAME)
  //       2) (integer) 30001                               <-- replica slot PORT
  //       3) "821d8ca00d7ccf931ed3ffc7e3db0599d2271abf"
  // 2) 1) (integer) 5461                                   <-- start slot range
  //    2) (integer) 8460                                   <-- end slot range
  //
  //    3) 1) "127.0.0.1"                                   <-- primary slot IP ADDR(HOSTNAME)
  //       2) (integer) 30001                               <-- primary slot PORT
  //       3) "09dbe9720cda62f7865eabc5fd8857c5d2678388"
  //
  //    4) 1) "127.0.0.1"                                   <-- replica slot IP ADDR(HOSTNAME)
  //       2) (integer) 30001                               <-- replica slot PORT
  //       3) "821d8ca00d7ccf931ed3ffc7e3db0599d2271def"
```
Our goal is to create different connection to keys that have hash slots 5400 (first range) and 8000(second range) for example, even though the host port is same i.e. 127.0.0.1 and 30001. Is there a way to achieve this?

**Comment by mp911de** [comment]
Connections for routing are keyed by hostname and IP, as the redirection mechanism uses the same keys. You cannot change the keying mechanism.

**Comment by ramaraochavali** [comment]
Thank you. If the proxy handles move/redirect would that be an option? In general is there a guidance on how to create multiple connections to a proxy so that we do not build the pipeline with commands hashing to different redis nodes where proxy handles the routing based on key?

**Comment by mp911de** [comment]
If your proxy handles routing, then why don't you use the Standalone Redis connection any perform any keying through an object pool?

**Comment by ramaraochavali** [comment]
Can standlone redis connection create multiple connections based on object pool? Can you please example?

**Comment by ramaraochavali** [comment]
@mp911de Any thoughts on ^^?

**Comment by tishun** [comment]
@ramaraochavali is this question still relevant?

**Comment by tishun** [comment]
> We went with alternative solutions. So not relevant any more

Thank you, will be closing this for now
