### ISSUE TITLE
Delay in cluster client detecting failover?

### ISSUE THREAD

**Issue by emilykimhuynh** [redis/lettuce#2308]
I have a cluster client configured with enableAllAdaptiveRefreshTriggers() and also call refreshPartitions() on every retry. From a Redis server perspective, failover occurs in < 5 seconds, but the client is taking upward to 30 seconds to adjust. Is this gap between client and server expected with this configuration, and if so, why? (Apologies if this is outlined in documentation somewhere, I was unable to find it).

**Comment by mp911de** [comment]
Adaptive refresh triggers have a timeout of 30 seconds to back off from event bursts. This is to protect the cluster from rapid connects/disconnects and topology retrievals.

**Comment by karlvr** [comment]
We are seeing similar behaviour on our Redis cluster of seven nodes; 3 × primary and 4 × replica. When we failover one of our primaries to a replica we get Lettuce threads hanging for 30-60s, and then just coming right, whereas the Reds failover appears to occur within ~1s.

We have set:

```java
	.enableAllAdaptiveRefreshTriggers()
	.adaptiveRefreshTriggersTimeout(Duration.ofSeconds(2))
```

... to attempt to encourage Lettuce to unblock itself, but without success. We would _love_ to get to the bottom of this as it makes it challenging for us to maintain Redis nodes. We can reproduce the issue easily in our setup and we're happy to test configuration!

This is our full client config:

```java
final ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
	.enablePeriodicRefresh(Duration.of(15, ChronoUnit.MINUTES))
	.enableAllAdaptiveRefreshTriggers()
	.adaptiveRefreshTriggersTimeout(Duration.ofSeconds(2))
	.closeStaleConnections(true)
	.build();

final SocketOptions socketOptions = SocketOptions.builder()
	.connectTimeout(Duration.of(5, ChronoUnit.SECONDS))
	.tcpNoDelay(true)
	.build();

client.setOptions(ClusterClientOptions.builder()
	.autoReconnect(true)
	/* Filter out failed nodes https://github.com/lettuce-io/lettuce-core/issues/2318 */
	.nodeFilter(node -> !node.getFlags().contains(NodeFlag.FAIL))
	.timeoutOptions(TimeoutOptions.enabled())
	.pingBeforeActivateConnection(true)
	.topologyRefreshOptions(topologyRefreshOptions)
	.socketOptions(socketOptions)
	.build());
```

**Comment by mp911de** [comment]
Can you record debug logs from the failover period? If we see what happens under the hood, then we might be able to identify what takes so long.
