### ISSUE TITLE
RedisClusterNode.hasSameSlotsAs() is unreliable 

### ISSUE THREAD

**Issue by jacob-pro** [redis/lettuce#2341]
#### Current Behavior

When using the `RedisClusterNode::hasSameSlotsAs()` function to compare nodes retrieved from `RedisClusterClient::getPartitions()` against nodes from `ClusterPartitionParser::parse` (via `RedisClusterCommands::clusterNodes`) it incorrectly returns false.

This is because the nodes in the client partitions table have a slot range of `null` whereas the parsed nodes have a non null but empty slot range.

The parsed nodes are created with a non-null BitSet even if they have no slots:

https://github.com/lettuce-io/lettuce-core/blob/fc6630e0fdd46e175e1d51a2491732092bb683ff/src/main/java/io/lettuce/core/cluster/models/partitions/RedisClusterNode.java#L102-L103

Whereas cloned nodes are created with a null BitSet if the slots are empty:

https://github.com/lettuce-io/lettuce-core/blob/fc6630e0fdd46e175e1d51a2491732092bb683ff/src/main/java/io/lettuce/core/cluster/models/partitions/RedisClusterNode.java#L122-L125

Updating the slots also leaves the value as null if the new range is empty:

https://github.com/lettuce-io/lettuce-core/blob/fc6630e0fdd46e175e1d51a2491732092bb683ff/src/main/java/io/lettuce/core/cluster/models/partitions/RedisClusterNode.java#L332-L334

#### Environment

- Lettuce version(s): 6.2.3.RELEASE
- Redis version: 7.0.8

#### Additional context

Similar / related to:

https://github.com/lettuce-io/lettuce-core/issues/1091
https://github.com/lettuce-io/lettuce-core/issues/1089

**Comment by mp911de** [comment]
It makes sense to fix this problem. Since you've looked already into it, do you want to submit a pull request along with a few unit test cases?

**Comment by zeze1004** [comment]
On second thought🤔🤔🤔, don't need to check the conditions to assigned a slot when creating a node. Just check if it's slot.empty().

What do you think of my opinion? Please review it.🙇🏻🙇🏻🙇🏻
