### ISSUE TITLE
Huge variation in key lookup times against redis cluster

### ISSUE THREAD

**Issue by menacher** [redis/lettuce#2436]
## Bug Report

I see a huge variation for looking up a key.  Some timings(in milliseconds) are as follows 9790ms, 28617ms,21474ms,5104ms,37ms,10ms,1ms,97ms,12957ms,1868ms

#### Current Behavior

<details>
<summary>Stack trace</summary>

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
RedisAdvancedClusterCommands<String, String> readSync = clusterConnection.sync();
String value = readSync.get(key);
```

</details>

#### Environment

- Lettuce version(s): io.lettuce:lettuce-core:jar:6.1.10.RELEASE
- Redis version: Keydb version 6

#### Additional context
I tried the same with Redisson library and it is very consistently fetching the key in less than 5ms.
This seems to happen only with cluster connection.

**Comment by mp911de** [comment]
Can you provide a debug/trace log from `GET` where it takes 20 seconds?

**Comment by menacher** [comment]
Hi, I have some limitations on setting up the tracing in the server I tested in. So, I created a local example where the Redis cluster is run locally in docker.  This does not show the timing variation as much as the server but still I could see times from 1ms to 100's of ms. I have added brave tracing library, let me know if I have set it up right in the file `KeycacheConfig.java`

I am attaching the example program I used to test this out.
[keycache.zip](https://github.com/lettuce-io/lettuce-core/files/11974033/keycache.zip)

*Usage is as follows:*.   
1.  Set a timeout `curl -XPOST http://localhost:8080/timeout/5000` note this is in nano seconds, so 5000 is actually 5 ms.
2. Create a key `curl -XPOST http://localhost:8080 -H 'Content-Type: application/json' --data-raw '{"key": "cluster", "value":"works"}'`
3. Read back the key `http://localhost:8080\?key\=cluster`
4. Run a basic load test `for i in {1..500}; do ((curl http://localhost:8080\?key\=cluster)&); done`
