### ISSUE TITLE
How to properly set the ClientOption requestQueueSize and how to monitor/log the requestQueueSize at runtime?

### ISSUE THREAD

**Issue by y2241** [redis/lettuce#2506]
Hi, we are using single connection per jvm (as pooled connection did not show better result for us). We are on lettuce 6.2+ version.
We have experienced redis command slowness from time to time (not always), such as a simple GET by key (its value is just a number for rate limiting implementation) could take 200ms, while the aws redis seemed to perform fine during these times. So I am trying to figure out how to improve our performance to make it more consistently fast and figure out where the bottom neck is.
1) I read about requestQueueSize in ClientOption. We currently set it as 1000. But not knowing what a proper value should be and what the significance of this value.
2) Also, is there way to access this requestQueue so that when the slowness occurs, we can see how many requests are blocked in the queue.
Any suggestion on debugging/trouble shooting is welcome.

Thanks

**Comment by craigpastro** [comment]
Hi! I was searching for exactly how to monitor the queue size as we are also running into a command slowness from time to time. Did you find any way to get the current size of the request queue? Thank you!
