### ISSUE TITLE
Feature to connect to redis-cluster hostdomain from lettuce

### ISSUE THREAD

**Issue by sdYoo** [redis/lettuce#2508]
#### Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. Ex. I have an issue when [...]

Hello,

When connecting to redis-cluster, I want to connect to the host domain.
I confirmed that it was possible to connect to individual nodes. 
However, I need the ability to connect only with the host information of redis-cluster.

Please provide the ability to connect only to the host of redis-cluster. 
If there is an existing method, please provide guidance.

Thanks 

#### Describe the solution you'd like

I want to connect only with the host name, rather than defining each node as shown below.

To-Be

        val clusterConfig = RedisClusterConfiguration().apply{
            this.setClusterHost("redis-cluster.com:6379")
            this.password   = RedisPassword.of(redisPassword)
        }

As-Is

       val node1 = RedisNode("1.1.1.1",6379)
        val node2 = RedisNode("1.1.1.2",6379)
        val node3 = RedisNode("1.1.1.3",6379)
        val clusterConfig = RedisClusterConfiguration().apply{
            this.setClusterNodes(setOf(node1, node2, node3))
            this.password   = RedisPassword.of(redisPassword)
        }

As-Is full code

       val node1 = RedisNode("1.1.1.1",6379)
        val node2 = RedisNode("1.1.1.2",6379)
        val node3 = RedisNode("1.1.1.3",6379)
        val clusterConfig = RedisClusterConfiguration().apply{
            this.setClusterNodes(setOf(node1, node2, node3))
            this.password   = RedisPassword.of(redisPassword)
        }
        val options = ClientOptions.builder()
            .disconnectedBehavior(ClientOptions.DisconnectedBehavior.REJECT_COMMANDS)
            .autoReconnect(true)
            .socketOptions(SocketOptions.builder()
            .keepAlive(SocketOptions.KeepAliveOptions.builder()
                .enable(true)
                .build()
             ).build())
            .build()
        val clientConfig = LettuceClientConfiguration.builder()
            .clientOptions(options)
            .commandTimeout(redisCommandTimeout)
            .build()
        return LettuceConnectionFactory(clusterConfig, clientConfig)

#### Teachability, Documentation, Adoption, Migration Strategy

If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

**Comment by mp911de** [comment]
How is the client supposed to resolve the initial cluster node? Generally, if there's an `A` or `AAAA` DNS record, then you can use `redis-cluster.com` already.

**Comment by sdYoo** [comment]
@mp911de 
Can I get a lettuce sample code based on kotlin that connects to the host of redis-cluster?

**Comment by sdYoo** [comment]
@mp911de
thank you! As you guid, I entered the domain instead of the server IP and it connected normally!

**Comment by tishun** [comment]
I am assuming the issue is resolved. Please reopen in case you are still facing an issue.
