### ISSUE TITLE
FIFO order is not respected in DefaultEndpoint#notifyChannelActive()

### ISSUE THREAD

**Issue by leisurelyrcxf** [redis/lettuce#2598]
## Bug Report

FIFO order is not respected in DefaultEndpoint#notifyChannelActive()

#### Current Behavior

A later write from the same user thread may be sent first

<details>

```java

@Test
    void writeShouldGuaranteeFIFOOrder() {
        sut.write(Collections.singletonList(new Command<>(CommandType.SELECT, new StatusOutput<>(StringCodec.UTF8))));

        sut.registerConnectionWatchdog(connectionWatchdog);
        doAnswer(i -> sut.write(new Command<>(CommandType.AUTH, new StatusOutput<>(StringCodec.UTF8)))).when(connectionWatchdog)
                .arm();
        when(channel.isActive()).thenReturn(true);

        sut.notifyChannelActive(channel);

        DefaultChannelPromise promise = new DefaultChannelPromise(channel, ImmediateEventExecutor.INSTANCE);

        when(channel.writeAndFlush(any())).thenAnswer(invocation -> {
            if (invocation.getArguments()[0] instanceof RedisCommand) {
                queue.add((RedisCommand) invocation.getArguments()[0]);
            }

            if (invocation.getArguments()[0] instanceof Collection) {
                queue.addAll((Collection) invocation.getArguments()[0]);
            }
            return promise;
        });

        assertThat(queue).hasSize(2).first().hasFieldOrPropertyWithValue("type", CommandType.SELECT);
        assertThat(queue).hasSize(2).last().hasFieldOrPropertyWithValue("type", CommandType.AUTH);
    }
```

```java
// your stack trace here;
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Expected behavior/code

```
assertThat(queue).hasSize(2).first().hasFieldOrPropertyWithValue("type", CommandType.SELECT);
assertThat(queue).hasSize(2).last().hasFieldOrPropertyWithValue("type", CommandType.AUTH);
```

#### Environment

- Lettuce version(s): [e.g. 5.0.0.RELEASE, 4.2.2.Final]
- Redis version: [e.g. 4.0.9]

**Comment by okg-cxf** [comment]
propose a fix: https://github.com/lettuce-io/lettuce-core/pull/2597

**Comment by mp911de** [comment]
Good catch. How did you encounter the issue?

Looking at the PR, it generally makes sense to hold a `volatile Channel` in a local variable to avoid any races. Generally speaking, while all notification methods should be invoked sequentially, there's nothing that would prevent the code from being called concurrently.

**Comment by okg-cxf** [comment]
> Good catch. How did you encounter the issue?
> 
> Looking at the PR, it generally makes sense to hold a `volatile Channel` in a local variable to avoid any races. Generally speaking, while all notification methods should be invoked sequentially, there's nothing that would prevent the code from being called concurrently.

The `public <K, V, T> RedisCommand<K, V, T> write(RedisCommand<K, V, T> command)` method is called in user threads and can be called concurrently with the netty eventloop io thread. The out-of-order could happen for the following execution order (supposing initially `channel = null`)

User Thread: `write(command1)`;  
Netty IO thread: `notifyChannelActive()# this.channel = channel;` (line 440); 
User Thread: `write(command2)`, now he sees the channel is set, and it grabs the shared lock and uses the channel to send `command2`; 
Netty IO thread:  `notifyChannelActive()# flushCommands()` (line 477), this will flush `command1`.

**Comment by okg-cxf** [comment]
@mp911de any updates?

**Comment by tishun** [comment]
I've spent some time looking at the test case you've prepared.
I think it is a valid (albeit corner case) scenario, that might result in commands being executed in the wrong order.

Let's continue the discussion in #2597
