### ISSUE TITLE
lettuce client keeps reconnecting redis

### ISSUE THREAD

**Issue by shivangivar** [redis/lettuce#2609]
Getting continuous Info logs that lettuce is trying to reconnect redis . These Info logs are printing in my application how can i stop it? Can you give me proper configuration for same for my application code.

These are my cluster logs 

![image](https://github.com/lettuce-io/lettuce-core/assets/64467134/4fed5271-b56a-4c59-a8ff-c94fd38ef822)

```
@Configuration
public class RedisConfig {

    @Value("${spring.data.redis.host}")
    private String redisHost;

    @Value("${spring.data.redis.password}")
    private String redisPassword;

    @Value("${spring.data.redis.port}")
    private int redisPort;

    @Profile("dev")
    @Bean
    public LettuceConnectionFactory redisConnectionFactory() {
        RedisStandaloneConfiguration configuration = new RedisStandaloneConfiguration(redisHost,redisPort);
        configuration.setPassword(redisPassword);
        return new LettuceConnectionFactory(configuration);
    }

    @Bean
    public RedisTemplate<String, Object> redisTemplate() {
        RedisTemplate<String, Object> redisTemplate = new RedisTemplate<>();
        redisTemplate.setConnectionFactory(redisConnectionFactory());
        // Configure serializers for keys and values
        redisTemplate.setKeySerializer(new StringRedisSerializer());
        redisTemplate.setValueSerializer(new GenericJackson2JsonRedisSerializer());
        redisTemplate.setHashKeySerializer(new StringRedisSerializer());
        redisTemplate.setHashValueSerializer(new GenericJackson2JsonRedisSerializer());

        // Enable transaction support, if needed
        redisTemplate.setEnableTransactionSupport(true);
        return redisTemplate;
    }
}
```

@mp911de    please help me what should I change so that these info logs stop coming as the amount of logs are more than the other logs so visibility is not there for me.

**Comment by tishun** [comment]
Hey @shivangivar ,
This is a configuration setting you need to implement on your side. Depending on the framework used and the way you configure it the steps differ. Please consult the documentation of the logger for how you can disable INFO level messages on a fine grained level (class or package)
