### ISSUE TITLE
Add support for JSON.NUMMULTBY

### ISSUE THREAD

**Issue by chayim** [redis/lettuce#2632]
Add support for the redis command JSON.NUMMULTBY as described [here](https://redis.io/commands/JSON.NUMMULTBY).

Note: This is autogenerated, meaning the issue will be close manually, for commands that are not designed to be used via a client.

**Comment by tishun** [comment]
JSON.NUMMULTBY is [deprecated since 2.0](https://github.com/RedisJSON/RedisJSON/blob/master/commands.json#L229)
