### ISSUE TITLE
Add support for JSON.RESP

### ISSUE THREAD

**Issue by chayim** [redis/lettuce#2644]
Add support for the redis command JSON.RESP as described [here](https://redis.io/commands/JSON.RESP).

Note: This is autogenerated, meaning the issue will be close manually, for commands that are not designed to be used via a client.

**Comment by yisraelU** [comment]
This is a deprecated
> As of JSON version 2.6, this command is regarded as deprecated.

**Comment by tishun** [comment]
> This is a deprecated
> 
> > As of JSON version 2.6, this command is regarded as deprecated.

Agreed
