### ISSUE TITLE
Add support for redisjson

### ISSUE THREAD

**Issue by chayim** [redis/lettuce#2648]
- [x] #2622 
- [x] #2623 
- [x] #2624 
- [x] #2625 
- [x] #2626
- [x] #2627 
- [x] #2628
- [x] #2629 
- [x] #2630 
- [x] #2631 
- [x] #2632
- [x] #2633
- [x] #2634 
- [x] #2635 
- [x] #2636 
- [x] #2637 
- [x] #2638
- [x] #2639
- [x] #2640 
- [x] #2641
- [x] #2642
- [x] #2643 
- [x] #2644 
- [x] #2645
- [x] #2646
- [x] #2647

**Comment by yisraelU** [comment]
@chayim This sounds like an interesting problem to solve and I'd be happy to have a go at it.
IArethere any design docs available for this ? or general design principles to follow

**Comment by tishun** [comment]
> @chayim This sounds like an interesting problem to solve and I'd be happy to have a go at it. IArethere any design docs available for this ? or general design principles to follow
Hey @yisraelU, apologies that this was not reflected, but we are already working on a solution to this.

**Comment by yisraelU** [comment]
@tishun Awesome , certainly no need to apologize, and thank you for all your hard work. Looking forward

**Comment by tishun** [comment]
See https://github.com/redis/lettuce/pull/2992
