### ISSUE TITLE
Kotlin ExperimentalLettuceCoroutinesApi annotation on sync multi DSL block is necessary?

### ISSUE THREAD

**Issue by craigpastro** [redis/lettuce#2822]
## Feature Request

I am not sure if this is a feature request or a question, but I am attempting to use the Kotlin `multi` transaction DSL block with sync commands and my IDE keeps telling me that I should add the ExperimentalLettuceCoroutinesApi annotation, but that can't be true with sync commands can it? So perhaps this line https://github.com/redis/lettuce/blob/c603c8120f7eab90cabb1a9a3ea321d1e3825799/src/main/kotlin/io/lettuce/core/api/sync/RedisSyncCommandsExtensions.kt#L31 is unnecessary?

But actually, I noticed that like appears in all the CommandsExtensions files... so maybe it is meant to be there.

#### Is your feature request related to a problem? Please describe

It is not related to a problem.

#### Describe the solution you'd like

Remove the annotation. Happy to make a PR if it is actually not necessary.

#### Describe alternatives you've considered

Perhaps the annotation is actually required.

**Comment by mp911de** [comment]
We're in the process of promoting coroutines into proper API with #2527

For the time being, classes using our coroutine extensions must be annotated with `@OptIn(ExperimentalLettuceCoroutinesApi::class)`

**Comment by craigpastro** [comment]
Hi @mp911de! Thanks for the reply. Okay, I see. I thought because I wasn't actually using `RedisCoroutinesCommands` or anywhere `.coroutines()`, and just `RedisCommands` with `.sync()` that I shouldn't need the annotation.
