### ISSUE TITLE
Deadlock in SharedLock

### ISSUE THREAD

**Issue by project-snail** [redis/lettuce#2905]
# Bug Report
When using the reactor client and performing Redis operations within the onErrorResume block,
there is a chance of encountering thread deadlock. This can impact all threads at the entry points.

## Reproduction steps are as follows:
1. Start Redis normally
2. Start the service
3. ab -c 3 -n 100000 http://127.0.0.1:18080/lettuce/get (simulate normal traffic)
4. Stop Redis (simulate Redis failure)
5. Start any process on the Redis port (simulate Redis IP and port being accessible but Redis not yet providing service)
6. Wait 30 seconds (wait for Lettuce to automatically reconnect to Redis, triggering the deadlock issue)
7. After stopping ab, the HTTP service still does not work properly. And upon querying jstack, it is confirmed that a deadlock has occurred.

![lockWritersExclusive](https://github.com/redis/lettuce/assets/38575998/1e9a5422-5890-4a15-abe7-5a7587f128c8)

![incrementWriters](https://github.com/redis/lettuce/assets/38575998/bd0c17ce-55fa-48b7-8baf-f59f874c0621)

## Environment
- lettuce-core 6.1.9.RELEASE

## Full demo code here
[demo_code.zip](https://github.com/user-attachments/files/16025218/lettuce_err.zip)

**Comment by tishun** [comment]
Quite possibly the same problem as the one in #2879

**Comment by tishun** [comment]
@project-snail thank you for the verbose bug report!
I think we actually need to prioritize this fix for one of the coming versions

**Comment by thachlp** [comment]
@project-snail 
I am a new contributor and would like to work on this.
I try to reproduce the issue but I can't.

**In step 3**, here is the output:
```
➜  ~ ab -c 3 -n 100000 http://127.0.0.1:18080/lettuce/get 
This is ApacheBench, Version 2.3 <$Revision: 1903618 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 10000 requests
apr_socket_recv: Operation timed out (60)
Total of 16333 requests completed
```
Does it what you expect?

**In step 5**, What I should do? I am using redis by Docker

Thanks 🙇

**Comment by tishun** [comment]
@thachlp did you also check the scenario in #2422 ?

**Comment by thachlp** [comment]
@tishun not yet, let me try
