### ISSUE TITLE
SPUBLISH not working for Reactive/Coroutines client when using pubsub connection

### ISSUE THREAD

**Issue by jkrauze** [redis/lettuce#2971]
## Bug Report

https://github.com/redis/lettuce/pull/2838/files#r1727231070

As per comment I left on that PR, the `spublish()` command in `RedisPubSubReactiveCommandsImpl` points to `publish` command instead of `spublish`.

This causes `spublish()` command to point to a wrong underlying command when using a pubsub connection (initiated with `.connectPubSub()` method).

Please note that the `spublish()` works fine when we use a regular connection.

#### Current Behavior

```kotlin
redisClient.connectPubSub().coroutines().spublish("test", "test")
```

this calls `PUBLISH test test`

```kotlin
redisClient.connect().coroutines().spublish("test", "test")
```

this calls `SPUBLISH test test`

#### Expected behavior/code

both should call `SPUBLISH test test`

#### Environment

- Lettuce version(s): 6.4.0.RELEASE
- Redis version: 7.0

#### Possible Solution

correct the typo

**Comment by jkrauze** [comment]
opened a PR fixing this typo

**Comment by tishun** [comment]
Wondering why the integration tests have not caught this issue. Please, give me a little time to verify that.

**Comment by tishun** [comment]
> Wondering why the integration tests have not caught this issue. Please, give me a little time to verify that.

Well the answer is we did not have tests for that :/

**Comment by tishun** [comment]
@jkrauze thank you for the contribution!
