### ISSUE TITLE
Allow client to override the hash slot assignment 

### ISSUE THREAD

**Issue by IshankGulati** [redis/lettuce#2977]
## Feature Request

Allow the client to override the hash slot assignment 

#### Is your feature request related to a problem? Please describe
I have a use case where we are storing a key composed of `{UUID}Integer` as a byte array in Redis where I expect only the UUID part to be used to assign a hash slot. The issue that we are facing is If the UUID contains characters 7b or 7d, it collides with `{` and `}` represented by ASCII byte values of 123 (0x7b) and 125 (0x7d) respectively which impacts the distribution of these keys.

Eg - 7d3e4567-e89b-12d3-a456-426614174000 gets printed as {}>Eg\xe8\x9b\x12\xd3\xa4VBf\x14\x17@\x00} when stored with hashtags in Redis.

#### Describe the solution you'd like

This can be solved if clients can override the hash slot assignment method here https://github.com/redis/lettuce/blob/d3c81497eeda1018ed6aa1861532a6d8cf33fa91/src/main/java/io/lettuce/core/cluster/SlotHash.java#L66

#### Describe alternatives you've considered

The alternative that we are considering is encoding the UUID part of the key in a custom manner where `7b` gets encoded as `80` and `7d` gets encoded as `81`. The opposite will be done when decoding these keys.

#### Teachability, Documentation, Adoption, Migration Strategy
To be added post assessing viability

**Comment by tishun** [comment]
Hey @IshankGulati ,

do you mind sharing a code sample where the issue is reproduced? I have several questions, but such an example would answer most of them. Thank you.

**Comment by IshankGulati** [comment]
Hi @tishun 
PFB a sample case.

```
    public static void main(String... args) {
        RedisURI redisURI = RedisURI.builder().withHost("")
                .withPort(6379).build();
        RedisClusterClient clusterClient = RedisClusterClient.create(redisURI);

        StatefulRedisClusterConnection<byte[], byte[]> conn = clusterClient.connect(ByteArrayCodec.INSTANCE);
        RedisAdvancedClusterCommands<byte[], byte[]> command = conn.sync();

        // sample value 
        byte[] value = {};

        int numKeys = 100;
        int i, j;
        UUID uuid = UUID.fromString("7d3e4567-e89b-12d3-a456-426614174000");
        byte[] userID = asByteArray(uuid);
        Random rand = new Random();
        for (i=0; i<numKeys/100; i++) {
            for (j=0;j<100;j++) {
                int randId = rand.nextInt(90000);
                byte[] randIdBytes = ByteBuffer.allocate(4).putInt(randId).array();
                byte startingBrace = (byte)'{';
                byte closingBrace = (byte)'}';
                byte [] key = new byte[22];
                key[0] = startingBrace;
                System.arraycopy(userID, 0, key, 1, userID.length);
                key[17] = closingBrace;
                System.arraycopy(randIdBytes, 0, key, 18, randIdBytes.length);
                command.set(key, value);
            }
        }
        clusterClient.shutdown();
    }

    public static byte[] asByteArray(UUID uuid) {
        ByteBuffer byteBuffer = ByteBuffer.wrap(new byte[16]);
        byteBuffer.putLong(uuid.getMostSignificantBits());
        byteBuffer.putLong(uuid.getLeastSignificantBits());
        return byteBuffer.array();
    }

```

**Comment by tishun** [comment]
Thank you for the sample, helped a lot in clarifying the case. Two notes on what I see:

### A. Redis server (and not the client) is responsible for hash allocation
This means that there is nothing we can do on the client side to influence how the server allocates the data, as we are simply passing to it the command and it parses the provided key to decide on the placement.

### B. The current contract works in [this way](https://stackoverflow.com/questions/40601023/redis-cluster-hashtag-for-a-key-which-is-a-byte-array)
And it would break the contract to change it for all the other users.

So IMHO the only solution you have is to make sure your hashtag generation method does not produce any of the control bytes as a result.

**Comment by IshankGulati** [comment]
@tishun As per Redis docs, I can see that usually the clients handle the hash slot allocation. Do you mean even after Lettuce sends a command to a node, Redis could redirect the command to another node or give an error?

Docs - https://redis.io/learn/operate/redis-at-scale/scalability/redis-cluster-and-client-libraries
Lettuce Code - https://github.com/redis/lettuce/blob/d3c81497eeda1018ed6aa1861532a6d8cf33fa91/src/main/java/io/lettuce/core/cluster/SlotHash.java#L66

**Comment by IshankGulati** [comment]
@tishun Any update on this?
