### ISSUE TITLE
Implement the LCS command and deprecate STRALGO

### ISSUE THREAD

**Issue by tishun** [redis/lettuce#2987]
## Feature Request

Deprecate the STRALGO command and implement the LCS in its place

#### Is your feature request related to a problem? Please describe

With https://github.com/redis/redis/issues/9744 the STRALGO command was deprecated in Redis 7.0
Tests that test the STRALGO command have not been running since the pipeline only uses latest Redis versions

#### Describe the solution you'd like

Implement the [LCS](https://redis.io/docs/latest/commands/lcs/) command

#### Describe alternatives you've considered

For users of the Lettuce driver the only possible solution now is to use the [Custom commands](https://redis.github.io/lettuce/advanced-usage/#custom-commands)

**Comment by tishun** [comment]
See also #2970

**Comment by injae-kim** [comment]
PR: https://github.com/redis/lettuce/pull/3037
