### ISSUE TITLE
ClassNotFoundException: com.fasterxml.jackson.core.JsonProcessingException

### ISSUE THREAD

**Issue by zeitlinger** [redis/lettuce#2993]
#### Current Behavior

![image](https://github.com/user-attachments/assets/23089c1b-f924-407f-8208-746eb993855f)

if jackson is not present (it's optional)

#### Additional context

introduced in https://github.com/redis/lettuce/pull/2992

**Comment by tishun** [comment]
Thanks for the report!

This is definitely a bug, will work on fixing it before the official release.
