### ISSUE TITLE
Json commands not exposed in AsyncCluster 

### ISSUE THREAD

**Issue by yisraelU** [redis/lettuce#3048]
## Bug Report
 I am using the latest release **6.5.0** which has the recently added redisJson commands (Thank you and Great Job!).

 Using the ```StatefulRedisClusterConnection``` , I can access either ```RedisAdvancedClusterCommands``` which gives me access to ```RedisJsonCommands``` through the simple inheritance model.
However when using the async member ```RedisAdvancedClusterAsyncCommands``` , it would appear that the ```RedisJsonAsyncCommands``` was left out of ```RedisClusterAsyncCommands``` [here](https://github.com/redis/lettuce/blob/39682dc931ec5de954e442f44f2bb162efdbcbf7/src/main/java/io/lettuce/core/cluster/api/async/RedisClusterAsyncCommands.java#L40) 

If this is intentional , what would the proper path forward be to access redisJson async commands for a cluster?

**Comment by tishun** [comment]
Hey @yisraelU ,
thanks for the report, yeah, this is something we overlooked.

Will work to fix it ASAP
