### ISSUE TITLE
LettuceConnectionFactory is not establishing the connection when using a Japanese username and password

### ISSUE THREAD

**Issue by ganeshgudaghe** [redis/lettuce#3071]
Hi,

I deployed Redis using a Japanese username and password, and when I try to make a connection from Spring Boot's LettuceConnectionFactory, it fails to establish a connection with the following error:

**"Caused by: io.lettuce.core.RedisCommandExecutionException: WRONGPASS invalid username-password pair or user is disabled."**

Even though I am using the correct username and password, I am able to connect using other tools like RedisInsight, but the issue is only with LettuceConnectionFactory.

```xml
                <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis</artifactId>
			<version>2.7.8</version>
		</dependency>
```
		
Below is my code:
userName="日本語"
password="日本語"
java
Copy code
```java
@Bean
public LettuceConnectionFactory lettuceConnectionFactory() {
    var config = new RedisStandaloneConfiguration(host, Integer.parseInt(port));
    var clientConfig = LettuceClientConfiguration.builder().build();
    config.setUsername(userName);
    config.setPassword(RedisPassword.of(password));
    return new LettuceConnectionFactory(config, clientConfig);
}

```
I also tried using UnifiedJedis, and it works fine:

java
Copy code
```java
HostAndPort config = new HostAndPort(host, port);
UnifiedJedis jedisClient = new UnifiedJedis(
    new PooledConnectionProvider(config, DefaultJedisClientConfig.builder().user(userName)
        .password(password).build()),
    maxAttempts, maxRetriesDuration);
```

**Comment by ganeshgudaghe** [comment]
@tishun could you please help me here to resolve this issue ?

**Comment by tishun** [comment]
Hey @ganeshgudaghe ,

I've reproduced the issue you are having. Seems that Lettuce is not handling these characters in a good way.
We need to prepare a fix and release it. For now I do not have a good workaround for you unfortunately (other than using english characters for username and password)

**Comment by ganeshgudaghe** [comment]
Thanks @tishun
