### ISSUE TITLE
[improvement] separate command execution reliability from auto reconnect

### ISSUE THREAD

**Issue by adamsau** [redis/lettuce#3072]
Is it possible to separate auto reconnect as a unique feature instead of depending on at-least-once reliability? we would like to use at-most once reliability, and at the same time let lettuce handle auto reconnection.
@tishun

**Comment by tishun** [comment]
Hey @adamsau ,

Can you confirm that what you are requesting is the same as the one in #1310 ?
If so we may have to bump the priority on it and try to get it done for some of the coming releases.

**Comment by adamsau** [comment]
@tishun 
yes, basically reliability does not need to follow auto reconnect mode

**Comment by tishun** [comment]
Closing this in favor of #1310
