### ISSUE TITLE
When the lettuce cannot connect to the Redis server, it feels like serial execution

### ISSUE THREAD

**Issue by ChenYingqin** [redis/lettuce#3113]
## Bug Report

maybe related：https://github.com/redis/lettuce/issues/2082;https://github.com/redis/lettuce/issues/1086
#### Current Behavior
When unable to connect to the Redis server, as the concurrency of the lettuce load test increases, the throughput rate will not change much, but the response time will increase exponentially

Using lettuce to connect to a port that is not a Redis service to simulate a timeout issue caused by Redis server hardware problems that prevent lettuce from connecting to the server. There is a strange phenomenon here, and I don't know what's going on. Can anyone help me? When I use 1 concurrent to perform stress testing on a web service, the QPS is 0.8. However, with 10 concurrent tests, QPS sometimes remains at 0.8. We know that lettuce is non blocking, and theoretically QPS should be 8

Screenshot of Test Records：
![image](https://github.com/user-attachments/assets/86a90b33-cdee-4647-a8d8-f4bd5d55c866)
![image](https://github.com/user-attachments/assets/f390a4cd-1dc5-472c-bc18-e0cb447cafc4)

<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
```
[lettuce-epollEventLoop-926-1] [i.l.c.c.t.DefaultClusterTopologyRefresh][344] - Unable to connect to [10.178.16.245:6380]: java.nio.channels.ClosedChannelException
io.lettuce.core.RedisConnectionException: Unable to establish a connection to Redis Cluster
	at io.lettuce.core.cluster.RedisClusterClient.lambda$assertInitialPartitions$26(RedisClusterClient.java:955)
	at io.lettuce.core.cluster.RedisClusterClient.get(RedisClusterClient.java:974)
	at io.lettuce.core.cluster.RedisClusterClient.assertInitialPartitions(RedisClusterClient.java:954)
	at io.lettuce.core.cluster.RedisClusterClient.connect(RedisClusterClient.java:406)
	at io.lettuce.core.cluster.RedisClusterClient.connect(RedisClusterClient.java:383)
</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/38293b67-e96a-4d2d-9502-5ead2985cbbc" />
<img width="1050" alt="image" src="https://github.com/user-attachments/assets/ae4b7ece-cfd1-4c5f-99d9-598d92608dcc" />

</details>

#### Environment
<img width="572" alt="image" src="https://github.com/user-attachments/assets/be7fb642-736f-43a1-ae86-793ddccc3e54" />

- Lettuce version(s): 6.5.1.RELEASE

**Comment by ChenYingqin** [comment]
i know the reason,each call requires the use of a different reactive connection

**Comment by tishun** [comment]
@ChenYingqin let me know if you need further assitance.
