### ISSUE TITLE
Chunked Pub/Sub message receive with interleaved command responses leaves commands uncompleted

### ISSUE THREAD

**Issue by GavinTianYang** [redis/lettuce#936]
lettuce version: 5.1.2.RELEASE

When i subscribe multi channels at one time, is there a problem? see blew.
```
// io.lettuce.core.pubsub.PubSubCommandHandler#decode
// when i call: pubSubCommands.subscribe("test1","test2","test3"...);
protected void decode(ChannelHandlerContext ctx, ByteBuf buffer) throws InterruptedException {
        if (!getStack().isEmpty()) {
            //first channel("test1") decoded here, and cmd polled from stack
            super.decode(ctx, buffer);
        }

        ReplayOutput<K, V> replay;
        while ((replay = queue.poll()) != null) {
            replay.replay(output);
            endpoint.notifyMessage(output);
            output = new PubSubOutput<>(codec);
        }

        while (super.getStack().isEmpty() && buffer.isReadable()) {
            // other channels decode here, like "test2" "test3"...
           // is this a problem here, in my opinion, all channels should decode on the first place where "test1" decoded.
            if (!super.decode(buffer, output)) {
                return;
            }
            endpoint.notifyMessage(output);
            output = new PubSubOutput<>(codec);
        }
        buffer.discardReadBytes();
    }
```

When i attempt to subscribe multi channels cyclic with 100 threads in one redis connection, I get an RedisCommandTimeoutException . 
Maybe you thought i shouldn't call it like this. But i truly have this requirement in my Application. 
Let's see the blew code.
```
// code in io.lettuce.core.pubsub.PubSubCommandHandler#decode
// when i call pubSubCommands.subscribe("test1","test2","test3"...) cyclic in 100 threads in one redis connection.
if (!super.decode(buffer, output)) {
       //channel "test2" "test3"... may be decoded here. image that, if super.decode(buffer, output)  
       //return false, it means the byte pack is not enough for "test2" decoding. Then function returned. 
       //at the same time, other thread put a command to stack. When netty channel get another bytes. 
       //we step this method at second time, super.decode(ctx, buffer) while perform nothing
       //because output.type() is not null. super.getStack().isEmpty() will be false, 
       //then the bytes will never be decoded .
                return;
}
```

If i just subscribe one channel. but there also maybe a problem.it same to previous problem.
Image that, if i get a message from a redis topic(channel),then decode message here
```
if (!super.decode(buffer, output)) {return}
```
if the message byte pack is not complete, super.decode(buffer, output) will return false and method return. at the same time i call a subscribe use the same connection, then output.type() will not be null, and super.getStack().isEmpty() will be false, we get a death loop, bytes will never be decoded ,like previous problem.

My Application use one connection to dynamic subscribe lots of channel，so I will  subscribe and receive  message at same time in multi threads.

**Comment by mp911de** [comment]
I do not understand what you're trying to explain. There are two decoding stages in Pub/Sub:

1. Decode command responses.
2. Decode out-of-band Pub/Sub messages.

Redis responds to `SUBSCRIBE foo bar` command with:

```
*3
$9
subscribe
$3
foo
:1
*3
$9
subscribe
$3
bar
:2
```

These are two responses. The first one is decoded using command response decoding to complete the `subscribe` command. The second response is just received as out-of-band response.

Multi-threaded usage is serialized by netty: You can write commands with multiple threads to a `Channel`, netty linearizes writes on a single I/O thread and reads/writes are effectively executed with single-threaded guarantees.

If you face a problem, please provide a simple reproducer. Firing random threads is not debuggable and not a reliable mechanism to reproduce an issue.

**Comment by mp911de** [comment]
Thanks a lot for the details, now I see the problem.

**Comment by Castill** [comment]
We have facing this problem recently. After timeout we cannot do any subscribe or unsubscribe under that connection. 

Our minimum reproduce code is under below. Hope that can help.

```java
public static void main(String[] args) {
    RedisClient client = RedisClient.create(
        RedisURI.builder()
            .withHost("localhost")
            .withPort(6379)
            .build()
    );

    client.setDefaultTimeout(Duration.ofSeconds(2));

    StatefulRedisPubSubConnection<String, String> subscribe = client.connectPubSub();
    StatefulRedisPubSubConnection<String, String> publish = client.connectPubSub();

    String payload = IntStream.range(0, 1024 * 3)
        .mapToObj(index -> "-")
        .collect(Collectors.joining());

    while (true) {
        try {
            subscribe.sync().subscribe("TEST");
            publish.sync().publish("TEST", payload);
        } catch (RedisCommandTimeoutException commandTimeoutException) {
            commandTimeoutException.printStackTrace();
            break;
        }
    }

    while (true) {
        try {
            subscribe.sync().subscribe("TEST");
        } catch (RedisCommandTimeoutException commandTimeoutException) {
            commandTimeoutException.printStackTrace();
        }
    }
}
```

**Comment by mp911de** [comment]
I pushed a change to our [feature branch for this ticket](https://github.com/lettuce-io/lettuce-core/tree/issues/gh-936) and the branch build that has produced artifact snapshots with version `5.2.0.gh936-SNAPSHOT`. Care to upgrade to see whether the change fixes your issue? The above mentioned reproducer no longer produces timeouts.

Make sure to include our snapshot repository:

```xml
<dependencies>
  <dependency>
    <groupId>io.lettuce</groupId>
    <artifactId>lettuce-core</artifactId>
    <version>5.2.0.gh936-SNAPSHOT</version>
  </dependency>
</dependencies>

<repositories>
  <repository>
    <id>sonatype-snapshots</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
```

**Comment by GavinTianYang** [comment]
> I pushed a change to our [feature branch for this ticket](https://github.com/lettuce-io/lettuce-core/tree/issues/gh-936) and the branch build that has produced artifact snapshots with version `5.2.0.gh936-SNAPSHOT`. Care to upgrade to see whether the change fixes your issue? The above mentioned reproducer no longer produces timeouts.
> 
> Make sure to include our snapshot repository:
> 
> ```
> <dependencies>
>   <dependency>
>     <groupId>io.lettuce</groupId>
>     <artifactId>lettuce-core</artifactId>
>     <version>5.2.0.gh936-SNAPSHOT</version>
>   </dependency>
> </dependencies>
> 
> <repositories>
>   <repository>
>     <id>sonatype-snapshots</id>
>     <url>https://oss.sonatype.org/content/repositories/snapshots</url>
>     <snapshots>
>       <enabled>true</enabled>
>     </snapshots>
>   </repository>
> </repositories>
> ```



> I pushed a change to our [feature branch for this ticket](https://github.com/lettuce-io/lettuce-core/tree/issues/gh-936) and the branch build that has produced artifact snapshots with version `5.2.0.gh936-SNAPSHOT`. Care to upgrade to see whether the change fixes your issue? The above mentioned reproducer no longer produces timeouts.
> 
> Make sure to include our snapshot repository:
> 
> ```
> <dependencies>
>   <dependency>
>     <groupId>io.lettuce</groupId>
>     <artifactId>lettuce-core</artifactId>
>     <version>5.2.0.gh936-SNAPSHOT</version>
>   </dependency>
> </dependencies>
> 
> <repositories>
>   <repository>
>     <id>sonatype-snapshots</id>
>     <url>https://oss.sonatype.org/content/repositories/snapshots</url>
>     <snapshots>
>       <enabled>true</enabled>
>     </snapshots>
>   </repository>
> </repositories>
> ```


> I pushed a change to our [feature branch for this ticket](https://github.com/lettuce-io/lettuce-core/tree/issues/gh-936) and the branch build that has produced artifact snapshots with version `5.2.0.gh936-SNAPSHOT`. Care to upgrade to see whether the change fixes your issue? The above mentioned reproducer no longer produces timeouts.
> 
> Make sure to include our snapshot repository:
> 
> ```
> <dependencies>
>   <dependency>
>     <groupId>io.lettuce</groupId>
>     <artifactId>lettuce-core</artifactId>
>     <version>5.2.0.gh936-SNAPSHOT</version>
>   </dependency>
> </dependencies>
> 
> <repositories>
>   <repository>
>     <id>sonatype-snapshots</id>
>     <url>https://oss.sonatype.org/content/repositories/snapshots</url>
>     <snapshots>
>       <enabled>true</enabled>
>     </snapshots>
>   </repository>
> </repositories>
> ```
yes, it fixed my issue!

**Comment by Castill** [comment]
@mp911de 

`5.2.0.gh936-SNAPSHOT` no longer exist in snapshot repository.

Is any estimate time `5.1.4` wil release ?

**Comment by mp911de** [comment]
The artifact was cleared out from the repository. 5.1.4 is scheduled for Feb 12.
